name: Shift Left Security Gate Pipeline


on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main



jobs:


# ============================
# SECRET SECURITY GATE
# ============================

  gitleaks:

    name: Secret Gate - Gitleaks

    runs-on: ubuntu-latest


    steps:


      - name: Checkout Code

        uses: actions/checkout@v4

        with:

          fetch-depth: 0



      - name: Run Gitleaks

        uses: gitleaks/gitleaks-action@v2

        env:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}





# ============================
# SAST SECURITY GATE
# ============================


  semgrep:


    name: Code Security Gate - Semgrep


    runs-on: ubuntu-latest



    steps:


      - name: Checkout Code

        uses: actions/checkout@v4



      - name: Install Semgrep

        run: |

          python -m pip install semgrep



      - name: Run Semgrep Security Gate

        run: |

          semgrep scan \
          --config p/security-audit \
          --config p/javascript \
          --error





# ============================
# DEPENDENCY SECURITY GATE
# ============================


  trivy:


    name: Dependency Security Gate - Trivy


    runs-on: ubuntu-latest



    steps:


      - name: Checkout Code

        uses: actions/checkout@v4



      - name: Run Trivy Security Gate


        uses: aquasecurity/trivy-action@master


        with:

          scan-type: fs

          scan-ref: .

          severity: HIGH,CRITICAL

          ignore-unfixed: true

          exit-code: 1


# ============================
# CONTAINER SECURITY GATE
# ============================


  container-security:


    name: Container Security Gate - Trivy


    runs-on: ubuntu-latest



    steps:


      - name: Checkout Code

        uses: actions/checkout@v4



      - name: Build Docker Image

        run: |

          docker build -t shift-left-app .



      - name: Scan Docker Image

        uses: aquasecurity/trivy-action@master


        with:

          image-ref: shift-left-app

          severity: HIGH,CRITICAL

          exit-code: 1

          ignore-unfixed: true


# ============================
# DAST SECURITY TEST - OWASP ZAP
# ============================

  zap-security:

    name: DAST Security Gate - OWASP ZAP

    runs-on: ubuntu-latest


    steps:

      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Build Docker Image

        run: |

          docker build -t shift-left-app .


      - name: Start Application

        run: |

          docker run -d \
          --name shift-left-container \
          -p 3000:3000 \
          shift-left-app


      - name: Wait for Application

        run: |

          sleep 15

          curl http://localhost:3000


      - name: OWASP ZAP Baseline Scan

        uses: zaproxy/action-baseline@v0.14.0

        with:

          target: 'http://localhost:3000'

          allow_issue_writing: false

          fail_action: false


      - name: Upload ZAP Report

        uses: actions/upload-artifact@v4

        with:

          name: zap-security-report

          path: report_html.html
# ============================
# SBOM GENERATION - SUPPLY CHAIN
# ============================

  sbom-security:

    name: SBOM Generation - Syft

    runs-on: ubuntu-latest


    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Install Syft

        uses: anchore/sbom-action/download-syft@v0


      - name: Generate CycloneDX SBOM

        run: |

          syft . \
          -o cyclonedx-json \
          > sbom.json


      - name: Upload SBOM Report

        uses: actions/upload-artifact@v4

        with:

          name: software-bill-of-materials

          path: sbom.json


# ============================
# SECURITY REPORT GENERATION
# ============================

  security-report:

    name: Generate Security Report

    runs-on: ubuntu-latest


    needs:
      - sbom-security


    steps:

      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Generate Report

        run: |

          chmod +x scripts/generate_report.sh

          ./scripts/generate_report.sh


      - name: Upload Security Report

        uses: actions/upload-artifact@v4

        with:

          name: devsecops-security-report

          path: reports/security-report.md
