name: Shift Left DevSecOps Pipeline


on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main



jobs:


# =====================
# Secret Detection
# =====================


  gitleaks:

    name: Secret Scan - Gitleaks

    runs-on: ubuntu-latest


    steps:


      - name: Checkout Repository
        uses: actions/checkout@v4



      - name: Install Gitleaks

        run: |

          wget https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_8.28.0_linux_x64.tar.gz

          tar -xzf gitleaks_8.28.0_linux_x64.tar.gz



      - name: Run Gitleaks

        run: |

          ./gitleaks detect \
          --source . \
          --report-format json \
          --report-path gitleaks-report.json || true



      - name: Upload Gitleaks Report

        uses: actions/upload-artifact@v4

        with:

          name: gitleaks-report

          path: gitleaks-report.json




# =====================
# SAST SCANNING
# =====================


  semgrep:


    name: SAST Scan - Semgrep


    runs-on: ubuntu-latest


    steps:


      - name: Checkout Repository

        uses: actions/checkout@v4



      - name: Run Semgrep

        uses: semgrep/semgrep-action@v1

        with:

          config: p/javascript

          generateSarif: "1"



      - name: Upload Semgrep Report

        uses: actions/upload-artifact@v4

        with:

          name: semgrep-report

          path: semgrep.sarif





# =====================
# Dependency Scanning
# =====================


  trivy:


    name: Dependency Scan - Trivy


    runs-on: ubuntu-latest


    steps:


      - name: Checkout Repository

        uses: actions/checkout@v4



      - name: Run Trivy

        uses: aquasecurity/trivy-action@master

        with:

          scan-type: fs

          scan-ref: .

          format: json

          output: trivy-report.json



      - name: Upload Trivy Report

        uses: actions/upload-artifact@v4

        with:

          name: trivy-report

          path: trivy-report.json
